BASE_URL = "https://qa-scooter.praktikum-services.ru/api/v1"

COURIER_ENDPOINT = f"{BASE_URL}/courier"
COURIER_LOGIN_ENDPOINT = f"{COURIER_ENDPOINT}/login"
COURIER_DELETE_ENDPOINT = f"{COURIER_ENDPOINT}/"  # ID будет добавляться динамически
ORDERS_ENDPOINT = f"{BASE_URL}/orders"

STATUS_OK = 200
STATUS_CREATED = 201
STATUS_BAD_REQUEST = 400
STATUS_NOT_FOUND = 404
STATUS_CONFLICT = 409

REQUEST_TIMEOUT = 5
